<?php

class antiBotStopList extends xPDOSimpleObject
{
    /**
     * Вернет IP в формате 0.0.0.0
     * @return string
     */
    public function getIp()
    {
        $ip = '';
        $ips = array_map('trim', $this->get(array('ip_1', 'ip_2', 'ip_3', 'ip_4')));
        if (count($ips)) {
            $ip = implode('.', $ips);
        }
        return $ip;
    }

    public function save($cacheFlag = null)
    {
        $this->set('ip', $this->getIp());
        return parent::save($cacheFlag); // TODO: Change the autogenerated stub
    }
}
