<?php
	# generated by EasyPack
	/** @var array $_lang */
	$_lang = array_merge(
		array (
  'extraExt.Deny' => 'Запретить',
  'extraExt.Deselect_All' => 'Отменить все',
  'extraExt.Select_All' => 'Выбрать все',
  'extraExt.action.html.search' => 'Найти <i class="fad fa-search"></i>',
  'extraExt.action.search' => 'Найти',
  'extraExt.add' => 'Добавить',
  'extraExt.allow' => 'Разрешить',
  'extraExt.create' => 'Создать',
  'extraExt.disable' => 'Отключить',
  'extraExt.enable' => 'Включить',
  'extraExt.enable.disable' => 'Включить/Выключить',
  'extraExt.failure' => 'неудача',
  'extraExt.html.failure' => '<span class="false">неудача</span>',
  'extraExt.html.search' => 'Поиск <i class="fad fa-search"></i>',
  'extraExt.html.success' => '<span class="true">успех</span>',
  'extraExt.increase' => 'Увеличить',
  'extraExt.link' => 'Ссылка',
  'extraExt.prefix' => 'Префикс',
  'extraExt.save' => 'Сохранить <i class="fas fa-save"></i>',
  'extraExt.search' => 'Поиск',
  'extraExt.select' => 'Выбрать',
  'extraExt.success' => 'успех',
  'extraExt.tables' => 'Таблицы',
  'extraExt.update' => 'Обновить',
  'extraExt.wrap' => 'Перенос',
)
		, $_lang);
	