<?php
include dirname(dirname(__FILE__)) . '/update.class.php';
class antiBotGuestEnableProcessor extends antiBotGuestUpdateProcessor
{
    public function initialize()
    {
        $ids = $this->modx->fromJSON($this->getProperty('ids'));
        if (empty($ids)) {
            return $this->failure($this->modx->lexicon('antibot_stoplist_err_ns'));
        }
        $this->setProperty('id',$ids[0]);
        return parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @return bool
     */
    public function beforeSet()
    {
        $this->setProperty('happy', true);
        return parent::beforeSet();
    }

}

return 'antiBotGuestEnableProcessor';
