<?php

class MyController1cOrderPayment extends modRestController
{
    /* @var fdkKassa $fdkKassa */
    public $fdkKassa;

    public function initialize()
    {


        include_once MODX_CORE_PATH . '/classes/fdkkassa.php';

        /* @var fdkKassa $fdkKassa */
        $this->fdkKassa = new fdkkassa($this->modx);
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function error($msg, $error = true)
    {

        $this->modx->getRequest();
        /* @var modResource $Resource */
        if ($Resource = $this->modx->getObject('modResource', 1394)) {
            $this->modx->resource = $Resource;
            $site_name = $this->modx->getOption('site_name');
            $mosPhone = $this->modx->getOption('mosPhone');

            if ($error) {
                $msg = '<p class="title error">' . $msg . '</p><p class="title error">Обратитесь по телефону</p><p class="title error">' . $mosPhone . '</p>';
            }

            $content = '
 <style>
                    .btn-success {
                        color: #fff !important;
                        background-color: #5cb85c !important;
                        border-color: #4cae4c !important;
                    }
                    .shoping_cart .shoping_cart-empty .content .btn.btn-lg {
                        height: 48px;
                        line-height: 46px;
                        font-size: 22px;
                    }
                    </style><p>&nbsp;</p>
<div class="shoping_cart">
<div class="container-fluid">
<div class="row">
<div class="col-md-12">
<div class="shoping_cart-empty">
<div class="content">
' . $msg . '
</div>
</div>
</div>
</div>
</div>
</div>';
            $this->modx->resource->set('pagetitle', $error ? "Ошибка оплаты" : 'Ссылка на оплату');
            $this->modx->resource->set('longtitle', $error ? "Ошибка оплаты" : 'Ссылка на оплату');
            $this->modx->resource->set('menutitle', $error ? "Ошибка оплаты" : 'Ссылка на оплату');
            $this->modx->resource->set('content', $content);
            $this->modx->request->prepareResponse();
            exit();
        }
    }

    /* @inheritdoc */
    public function get()
    {
        $order_1c_id = $this->getProperty('id');
        if (empty($order_1c_id)) {
            $this->error('Не передан order_1c_id заказа');
        } else {
            /* @var xPDOObject|msOrder $Order */
            if ($Order = $this->modx->getObject('msOrder', ['operation_uuid' => $order_1c_id])) {
                if ($Order->get('status') == 2) {
                    $this->error('Заказ уже был оплачен');
                }

                /* @var miniShop2 $ms2 */
                $ms2 = $this->modx->getService('miniShop2');
                $response = $this->fdkKassa->msOrderGerUrlPayment($Order);
                if ($response['success']) {
                    http_response_code(302);
                    // Автоматическое перенаправление без показа кнопка оплатить
                    $this->modx->sendRedirect($response['data']['redirect']);
                    exit();
                    $this->error($msg, false);
                } else {
                    $this->error($response['message']);
                }
            } else {
                $this->error('Заказ с номером ' . $order_1c_id . ' не найден');
            }
        }
    }
}
